// Round 4/danhosaurportfolioii/client/src/components/Projects/FilterLabel.vue
<template>
  <label>
    <b>{{ display }}</b>
    <input type="text" :list="`filter-data-${type}`" :value="inputValue" @input="valueChanged">
    <datalist :id="`filter-data-${type}`">
      <option :value="item" v-for="(item, i) in getProjects(type)" :key="i"></option>
    </datalist>
  </label>
</template>

<script>
import { Me } from 'models';

/**@props: { display: String, type: 'projectLanguage' | 'projectType', all: String, me: Me }
 * @emits change(type: 'language' | 'projectType', value: String)*/
export default {
    name: 'filter-label',
    props: {
        display: String,
        type: String,
        inputValue: String,
        me: Me
    },
    methods: {
        /**@param {'projectLanguage' | 'projectType'} type*/
        getProjects(type) {
            type = type == 'projectLanguage' ? 'language' : type;
            if (!this.me) return this.all;

            return [this.all, ...this.me.projects?.reduce((result, p) => {
                if (!result.includes(p[type]))
                    result.push(p[type])
                return result;
            }, []).sort() || []];
        },
        valueChanged(e) {
            this.$emit('change', this.type, e.target.value);
        }
    }
}
</script>

<style>

</style>

// Round 5/danhosaurportfolioiii/src/components/sites/Projects/FilterLabel.tsx
import { useMemo } from 'react'
import { useTranslate } from 'providers/LanguageProvider';
import { useMe } from 'providers/MeProvider';

export type FilterTypes = 'language' | 'projectType'
type Props = {
    value: string,
    onChange: (v: string) => void;
    type: FilterTypes
}

export default function FilterLabel({ value, onChange, type }: Props) {
    const translate = useTranslate();
    const { projects } = useMe();

    const values = useMemo(() => projects.reduce((result, acc) => {
        if (!result.includes(acc[type]) && acc.display) result.push(acc[type]);
        return result;
    }, new Array<string>()).map(v => (
        <option value={v} key={v} />
    )), [projects]);
    const id = `filter-data-${type}`;
    
    return (
        <label>
            <b>{translate(type)}</b>
            <input type="text" list={id} 
                value={value} onChange={e => onChange(e.target.value)} 
                placeholder={translate('all')}
            />
            <datalist id={id}>
                {values}
            </datalist>
        </label>
    )
}
