// Round 4/danhosaurportfolioii/client/src/components/Shared/LanguageSelector.vue
<template>
  <label id="language-selector">
      <b>{{ languageLabel }}</b>
      <input type="text" list="languages-list" :value="languageValue" @input="valueChanged">
      <datalist id="languages-list">
          <option :value="item" v-for="(item, i) in supportedLanguages" :key="i"></option>
      </datalist>
  </label>
</template>

<script>
import { languages } from '../../data';

/**@props { language: Map, languageValue: String }
 * @emits change(value: string)*/
export default {
    props: {
        language: Map,
        languageValue: String,
        supportedLanguages: languages.keys()
    },
    computed: {
        languageLabel() { 
            return this.language.get('language');
        }
    },
    methods: {
        valueChanged(e) {
            this.$emit('change', e.target.value);
        }
    }
}
</script>

<style>

</style>

// Round 5/danhosaurportfolioiii/src/components/shared/LanguageSelector/index.tsx
import { useEffect } from 'react'
import { useStateOnChange } from 'danholibraryrjs';
import { SupportedLanguages, useLanguage, useLanguages, useTranslate } from 'providers/LanguageProvider'
import './LanguageSelector.scss';

export default function LanguageSelector() {
    const translate = useTranslate();
    const [currentLanguage, setLanguage] = useLanguage();
    const [language, inputLanguage, setInput] = useStateOnChange(currentLanguage, 100);
    const languages = useLanguages();

    useEffect(() => {
        if (!languages.includes(language)) return;
        setLanguage(language);
    }, [language])

    return (
        <label id="language-selector">
            <p>{translate('language')}</p>
            <input type="text" value={inputLanguage} list='language-list' onChange={e => setInput(e.target.value as SupportedLanguages)}/>
            <datalist id='language-list'>
                {languages.map(lang => <option value={lang} key={lang} />)}
            </datalist>
        </label>
    )
}
